package vivero

import (
	"encoding/json"
	"fmt"
	"io"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"syscall"
	"time"
)

const defaultStartupConcurrency = 4

type serviceStartResult struct {
	name    string
	service PreviewService
	err     error
}

func startupConcurrency(resources ResourceConfig, serviceCount int) int {
	if serviceCount <= 0 {
		return 0
	}
	limit := resources.MaxStartupConcurrency
	if limit == 0 {
		limit = defaultStartupConcurrency
	}
	if limit < 1 {
		limit = 1
	}
	if limit > serviceCount {
		limit = serviceCount
	}
	return limit
}

func startServicesBounded(names []string, concurrency int, start func(name string) (PreviewService, error)) (map[string]PreviewService, error) {
	ordered := append([]string(nil), names...)
	sort.Strings(ordered)
	results := make(map[string]PreviewService, len(ordered))
	if len(ordered) == 0 {
		return results, nil
	}
	if concurrency <= 0 {
		concurrency = defaultStartupConcurrency
	}
	if concurrency > len(ordered) {
		concurrency = len(ordered)
	}

	resultCh := make(chan serviceStartResult, concurrency)
	errs := make(map[string]error)
	next := 0
	inFlight := 0
	stopping := false
	for next < len(ordered) || inFlight > 0 {
		for !stopping && next < len(ordered) && inFlight < concurrency {
			name := ordered[next]
			next++
			inFlight++
			go func() {
				service, err := start(name)
				resultCh <- serviceStartResult{name: name, service: service, err: err}
			}()
		}
		if inFlight == 0 {
			break
		}
		result := <-resultCh
		inFlight--
		results[result.name] = result.service
		if result.err != nil {
			errs[result.name] = result.err
			stopping = true
		}
	}
	for _, name := range ordered {
		if err := errs[name]; err != nil {
			return results, err
		}
	}
	return results, nil
}

func (a *App) startAppServices(req UpRequest, cfg ProjectConfig, sources map[string]PreviewSource, services map[string]PreviewService) error {
	names := sortedMapKeys(cfg.Services)
	started, err := startServicesBounded(names, startupConcurrency(cfg.Resources, len(names)), func(name string) (PreviewService, error) {
		ps, err := a.startService(req, name, cfg.Services[name], sources, cfg, req.Public, true)
		if err != nil {
			a.recordEvent(req.ID, "error", "service.failed", err.Error(), name, nil)
			return ps, fmt.Errorf("start service %s: %w", name, err)
		}
		if err := a.saveService(req.ID, ps); err != nil {
			a.recordEvent(req.ID, "error", "service.failed", err.Error(), name, nil)
			return ps, fmt.Errorf("save service %s: %w", name, err)
		}
		return ps, nil
	})
	for _, name := range sortedMapKeys(started) {
		services[name] = started[name]
	}
	return err
}

func (a *App) startBackingServices(req UpRequest, cfg ProjectConfig, sources map[string]PreviewSource, services map[string]PreviewService) error {
	names := sortedMapKeys(cfg.BackingServices)
	started, err := startServicesBounded(names, startupConcurrency(cfg.Resources, len(names)), func(name string) (PreviewService, error) {
		svc := serviceConfigForBacking(cfg.BackingServices[name])
		ps, err := a.startService(req, name, svc, sources, cfg, false, false)
		if err != nil {
			return ps, fmt.Errorf("start backing service %s: %w", name, err)
		}
		if err := a.saveService(req.ID, ps); err != nil {
			return ps, fmt.Errorf("save backing service %s: %w", name, err)
		}
		return ps, nil
	})
	for _, name := range sortedMapKeys(started) {
		services[name] = started[name]
	}
	return err
}

func (a *App) writeComposeManifest(previewID string, cfg ProjectConfig, sources map[string]PreviewSource) error {
	var b strings.Builder
	b.WriteString("# Generated by Vivero for inspection/debugging. Vivero launches app services through the Docker-compatible runtime adapter.\n")
	b.WriteString("services:\n")
	for _, name := range sortedMapKeys(cfg.Services) {
		svc := cfg.Services[name]
		b.WriteString("  " + name + ":\n")
		if serviceRuntime(svc) == "compose" {
			b.WriteString("    # Runtime delegated to app-owned Compose stack.\n")
			b.WriteString("    x-vivero-runtime: compose\n")
			if files := composeFiles(svc.Compose); len(files) > 0 {
				b.WriteString("    x-vivero-compose-files:\n")
				for _, file := range files {
					b.WriteString("      - " + quoteYAML(file) + "\n")
				}
			}
			b.WriteString("    x-vivero-compose-service: " + quoteYAML(composeServiceName(svc.Compose, name)) + "\n")
		} else if svc.Image != "" {
			b.WriteString("    image: " + svc.Image + "\n")
		} else {
			b.WriteString("    image: scratch\n")
		}
		if !svc.Command.IsZero() {
			b.WriteString("    command: " + runtimeCommandYAML(svc.Command) + "\n")
		}
		ports, err := servicePortPlan(svc)
		if err != nil {
			return err
		}
		if len(ports) > 0 {
			b.WriteString("    ports:\n")
			for _, port := range ports {
				if port.Host > 0 {
					b.WriteString(fmt.Sprintf("      - \"%s:%d:%d\"\n", port.HostIP, port.Host, port.Container))
				} else {
					b.WriteString(fmt.Sprintf("      - \"%s::%d\"\n", port.HostIP, port.Container))
				}
			}
		}
		if svc.Source != "" && serviceRuntime(svc) != "compose" {
			if src, ok := sources[svc.Source]; ok {
				b.WriteString("    volumes:\n      - " + src.Path + ":/app\n")
			}
		}
	}
	path := previewRunFilePath(a.Home, previewID, "compose.yml")
	if err := ensureDir(filepath.Dir(path)); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

func quoteYAML(s string) string { return fmt.Sprintf("%q", s) }

func runtimeCommandYAML(command RuntimeCommand) string {
	if len(command.Args) > 0 {
		encoded, err := json.Marshal(command.Args)
		if err == nil {
			return string(encoded)
		}
	}
	return quoteYAML(command.Shell)
}

func serviceConfigForBacking(backing BackingConfig) ServiceConfig {
	return ServiceConfig{
		Source:            backing.Source,
		Runtime:           backingRuntime(backing),
		Image:             backing.Image,
		Compose:           backing.Compose,
		Command:           backing.Command,
		Env:               backing.Env,
		Health:            backing.Health,
		DependencyVolumes: backing.DependencyVolumes,
		ResourceLimits:    backing.ResourceLimits,
	}
}

func (a *App) envForService(projectName string, svc ServiceConfig, includeSecrets bool) map[string]string {
	env := map[string]string{}
	if includeSecrets {
		secrets, _ := readEnvFile(a.secretFile(projectName))
		for k, v := range secrets {
			env[k] = v
		}
	}
	for k, v := range svc.Env {
		env[k] = v
	}
	return env
}

type headerRewriteProxyStarter func(previewID, service, runtime, containerID, originURL, hostHeader string, publicRewrite PublicRewriteConfig, routes []publicProxyRoute, h HealthConfig, listenHost string) (string, int, error)

func serviceIsPublic(svc ServiceConfig, forcePublic bool) bool {
	return forcePublic || svc.Public
}

func serviceNeedsHeaderRewriteProxy(svc ServiceConfig, routes []publicProxyRoute) bool {
	return strings.TrimSpace(svc.TunnelHostHeader) != "" || len(routes) > 0 || !isZeroPublicRewriteConfig(svc.PublicRewrite)
}

func publicProxyRoutesForService(ps PreviewService, svc ServiceConfig) []publicProxyRoute {
	ports, err := servicePortPlan(svc)
	if err != nil {
		return nil
	}
	routes := make([]publicProxyRoute, 0, len(ports))
	for _, port := range ports {
		if port.PublicPath == "" {
			continue
		}
		published, ok := ps.Ports[port.Name]
		if !ok || published.URL == "" {
			continue
		}
		hostHeader := ""
		for _, origin := range port.PublicOrigins {
			if parsed, parseErr := url.Parse(origin); parseErr == nil && parsed.Host != "" {
				hostHeader = parsed.Host
				break
			}
		}
		routes = append(routes, publicProxyRoute{Path: port.PublicPath, Target: published.URL, HostHeader: hostHeader, Origins: append([]string(nil), port.PublicOrigins...)})
	}
	return routes
}

func exposeServiceThroughHeaderRewriteProxy(previewID, name string, ps PreviewService, svc ServiceConfig, forcePublic bool, start headerRewriteProxyStarter) (PreviewService, string, error) {
	tunnelOriginURL := ps.OriginURL
	if tunnelOriginURL == "" {
		tunnelOriginURL = ps.URL
	}
	hostHeader := strings.TrimSpace(svc.TunnelHostHeader)
	routes := publicProxyRoutesForService(ps, svc)
	if tunnelOriginURL == "" || !serviceNeedsHeaderRewriteProxy(svc, routes) {
		return ps, tunnelOriginURL, nil
	}
	proxyURL, proxyPID, err := start(previewID, name, ps.Runtime, ps.ContainerID, tunnelOriginURL, hostHeader, svc.PublicRewrite, routes, svc.Health, svc.ProxyListenHost)
	if err != nil {
		return ps, tunnelOriginURL, err
	}
	if proxyURL == "" {
		return ps, tunnelOriginURL, fmt.Errorf("header rewrite proxy returned an empty URL")
	}
	ps.ProxyPID = proxyPID
	ps.ProxyPIDIdentity, _ = processIdentity(proxyPID)
	ps.ProxyURL = proxyURL
	tunnelOriginURL = proxyURL
	if !serviceIsPublic(svc, forcePublic) {
		ps.URL = proxyURL
	}
	return ps, tunnelOriginURL, nil
}

func (a *App) startService(req UpRequest, name string, svc ServiceConfig, sources map[string]PreviewSource, cfg ProjectConfig, forcePublic bool, includeSecrets bool) (PreviewService, error) {
	previewID := req.ID
	serviceTimer := startOperationTimer()
	runtime := serviceRuntime(svc)
	ports, err := servicePortPlan(svc)
	if err != nil {
		return PreviewService{Name: name, Source: svc.Source, Runtime: runtime, Status: "starting", Command: svc.Command.Display(), StartedAt: nowUTC()}, err
	}
	ps := PreviewService{Name: name, Source: svc.Source, Runtime: runtime, Status: "starting", Port: svc.Port, Command: svc.Command.Display(), StartedAt: nowUTC()}
	originURL := ""
	originHost := originHostForService(svc)
	if len(ports) > 0 && (forcePublic || svc.Public) && !isLoopbackHost(originHost) {
		return ps, fmt.Errorf("public service %s originHost must be loopback", name)
	}
	workdir := ""
	if svc.Source != "" {
		src, ok := sources[svc.Source]
		if !ok {
			return ps, fmt.Errorf("service %s references unknown source %s", name, svc.Source)
		}
		workdir = src.Path
		if svc.WorkingDir != "" {
			workdir = filepath.Join(workdir, svc.WorkingDir)
		}
	}
	env := a.envForService(cfg.Project.Name, svc, includeSecrets)
	logPath := serviceLogPath(a.Home, previewID, name, ".log")
	ps.LogPath = logPath
	if err := ensureDir(filepath.Dir(logPath)); err != nil {
		return ps, err
	}
	if runtime != "docker" && runtime != "compose" {
		return ps, fmt.Errorf("service %s has unsupported runtime %q; Vivero runs app services in containers only", name, runtime)
	}
	containerID, err := a.startDockerService(cfg.Project.Name, previewID, name, svc, sources, env)
	if err != nil {
		if runtime == "compose" {
			return ps, a.serviceFailureError(previewID, name, svc, ps, env, err)
		}
		return ps, err
	}
	ps.ContainerID = containerID
	cleanupStarted := func() error {
		var cleanupErr error
		ps, cleanupErr = a.stopPreviewServiceResources(previewID, name, ps)
		return cleanupErr
	}
	if len(ports) > 0 {
		published, err := a.containerRuntime().PublishedPorts(containerID, ports)
		if err != nil {
			if cleanupErr := cleanupStarted(); cleanupErr != nil {
				err = fmt.Errorf("%w; cleanup failed: %v", err, cleanupErr)
			}
			return ps, err
		}
		portMap, err := previewPortsFromPublished(ports, published, originHost)
		if err != nil {
			if cleanupErr := cleanupStarted(); cleanupErr != nil {
				err = fmt.Errorf("%w; cleanup failed: %v", err, cleanupErr)
			}
			return ps, err
		}
		ps.Ports = portMap
		if primary, ok := primaryPreviewPort(portMap); ok {
			ps.Port = primary.Host
			originURL = primary.URL
			ps.OriginURL = originURL
			ps.URL = originURL
		}
	}
	ensureRuntimeHealthy := func(phase string) error {
		if err := a.checkServiceRuntime(previewID, name, runtime, containerID); err != nil {
			ps.Status = "unhealthy"
			ps.LastHealth = err.Error()
			a.recordEvent(previewID, "error", "service.runtime_failed", err.Error(), name, map[string]string{"container": containerID, "phase": phase})
			failureErr := a.serviceFailureError(previewID, name, svc, ps, env, err)
			if cleanupErr := cleanupStarted(); cleanupErr != nil {
				failureErr = fmt.Errorf("%w; cleanup failed: %v", failureErr, cleanupErr)
			}
			_ = a.saveService(previewID, ps)
			return failureErr
		}
		return nil
	}
	if err := ensureRuntimeHealthy("started"); err != nil {
		return ps, err
	}
	_ = os.WriteFile(logPath, []byte("container "+containerID+" started via "+runtime+"\n"), 0o644)
	startMetadata := map[string]string{"container": containerID, "runtime": runtime, "command": svc.Command.Display()}
	if svc.Image != "" {
		startMetadata["image"] = svc.Image
	}
	a.recordEvent(previewID, "info", "service.started", "container started", name, serviceTimer.metadata(startMetadata))
	if workdir != "" {
		a.recordEvent(previewID, "info", "service.workdir", "container source mounted", name, map[string]string{"hostPath": workdir})
	}
	if !svc.Health.Command.IsZero() {
		timeout := serviceHealthTimeout(svc.Health, 30*time.Second)
		healthTimer := startOperationTimer()
		if err := a.containerRuntime().WaitHealthCommand(containerID, svc.Health, timeout); err != nil {
			ps.Status = "unhealthy"
			ps.LastHealth = err.Error()
			a.recordEvent(previewID, "error", "service.health_failed", err.Error(), name, healthTimer.metadata(map[string]string{"container": containerID}))
			failureErr := a.serviceFailureError(previewID, name, svc, ps, env, err)
			if cleanupErr := cleanupStarted(); cleanupErr != nil {
				failureErr = fmt.Errorf("%w; cleanup failed: %v", failureErr, cleanupErr)
			}
			_ = a.saveService(previewID, ps)
			return ps, failureErr
		}
		ps.Status = "healthy"
		ps.LastHealth = "ok"
		a.recordEvent(previewID, "info", "service.healthy", "health command passed", name, healthTimer.metadata(map[string]string{"container": containerID}))
		if err := ensureRuntimeHealthy("health_command"); err != nil {
			return ps, err
		}
	}
	if originURL != "" {
		timeout := serviceHealthTimeout(svc.Health, 30*time.Second)
		healthTimer := startOperationTimer()
		if err := a.waitHTTPForServiceRuntime(originURL, previewID, name, ps, svc.Health, timeout); err != nil {
			ps.Status = "unhealthy"
			ps.LastHealth = err.Error()
			a.recordEvent(previewID, "error", "service.health_failed", err.Error(), name, healthTimer.metadata(map[string]string{"url": originURL}))
			failureErr := a.serviceFailureError(previewID, name, svc, ps, env, err)
			if cleanupErr := cleanupStarted(); cleanupErr != nil {
				failureErr = fmt.Errorf("%w; cleanup failed: %v", failureErr, cleanupErr)
			}
			_ = a.saveService(previewID, ps)
			return ps, failureErr
		}
		ps.Status = "healthy"
		ps.LastHealth = "ok"
		a.recordEvent(previewID, "info", "service.healthy", "health check passed", name, healthTimer.metadata(map[string]string{"url": originURL}))
	}
	if originURL != "" {
		var tunnelOriginURL string
		var proxyErr error
		ps, tunnelOriginURL, proxyErr = exposeServiceThroughHeaderRewriteProxy(previewID, name, ps, svc, forcePublic, a.startHeaderRewriteProxy)
		if proxyErr != nil {
			if cleanupErr := cleanupStarted(); cleanupErr != nil {
				proxyErr = fmt.Errorf("%w; cleanup failed: %v", proxyErr, cleanupErr)
			}
			return ps, proxyErr
		}
		if serviceIsPublic(svc, forcePublic) {
			if isNamedPublicTunnel(cfg.Public) {
				url, err := publicURLForService(cfg.Public, req, name)
				if err != nil {
					if cleanupErr := cleanupStarted(); cleanupErr != nil {
						err = fmt.Errorf("%w; cleanup failed: %v", err, cleanupErr)
					}
					return ps, err
				}
				ps.URL = url
				if err := a.saveService(previewID, ps); err != nil {
					if cleanupErr := cleanupStarted(); cleanupErr != nil {
						err = fmt.Errorf("%w; cleanup failed: %v", err, cleanupErr)
					}
					return ps, err
				}
				tunnelTimer := startOperationTimer()
				if err := a.waitHTTPForServiceResources(url, previewID, name, ps, svc.Health, serviceHealthTimeout(svc.Health, 3*time.Minute)); err != nil {
					ps.Status = "unhealthy"
					ps.LastHealth = err.Error()
					a.recordEvent(previewID, "error", "tunnel.failed", err.Error(), name, tunnelTimer.metadata(map[string]string{"url": url, "origin": tunnelOriginURL}))
					err = fmt.Errorf("public named tunnel health failed for %s: %w", name, err)
					if cleanupErr := cleanupStarted(); cleanupErr != nil {
						err = fmt.Errorf("%w; cleanup failed: %v", err, cleanupErr)
					}
					_ = a.saveService(previewID, ps)
					return ps, err
				}
				a.recordEvent(previewID, "info", "tunnel.ready", "stable public URL health check passed", name, tunnelTimer.metadata(map[string]string{"url": url, "origin": tunnelOriginURL}))
				return ps, nil
			}
			tunnelTimer := startOperationTimer()
			url, pid, tlog, err := a.startQuickTunnel(previewID, name, tunnelOriginURL, "")
			if err != nil {
				a.recordEvent(previewID, "error", "tunnel.failed", err.Error(), name, tunnelTimer.metadata(map[string]string{"origin": tunnelOriginURL}))
				if cleanupErr := cleanupStarted(); cleanupErr != nil {
					err = fmt.Errorf("%w; cleanup failed: %v", err, cleanupErr)
				}
				return ps, err
			}
			ps.TunnelPID = pid
			ps.TunnelPIDIdentity, _ = processIdentity(pid)
			ps.TunnelLogPath = tlog
			ps.URL = url
			// Verify the public URL before returning it. Vivero's core guarantee is URL = works.
			if err := a.waitHTTPForServiceResources(url, previewID, name, ps, svc.Health, serviceHealthTimeout(svc.Health, 3*time.Minute)); err != nil {
				ps.Status = "unhealthy"
				ps.LastHealth = err.Error()
				a.recordEvent(previewID, "error", "tunnel.failed", err.Error(), name, tunnelTimer.metadata(map[string]string{"url": url, "origin": tunnelOriginURL}))
				err = fmt.Errorf("public tunnel health failed for %s: %w", name, err)
				if cleanupErr := cleanupStarted(); cleanupErr != nil {
					err = fmt.Errorf("%w; cleanup failed: %v", err, cleanupErr)
				}
				_ = a.saveService(previewID, ps)
				return ps, err
			}
			a.recordEvent(previewID, "info", "tunnel.ready", "public URL health check passed", name, tunnelTimer.metadata(map[string]string{"url": url, "origin": tunnelOriginURL}))
		}
	}
	if ps.Status == "starting" {
		ps.Status = "running"
	}
	return ps, nil
}

func quickTunnelArgs(originURL, hostHeader string) []string {
	args := []string{"tunnel", "--url", originURL, "--no-autoupdate"}
	if hostHeader != "" {
		args = append(args, "--http-host-header", hostHeader)
	}
	return args
}

func (a *App) startQuickTunnel(previewID, service, originURL, hostHeader string) (string, int, string, error) {
	if _, err := exec.LookPath("cloudflared"); err != nil {
		return "", 0, "", fmt.Errorf("cloudflared not found: %w", err)
	}
	logPath := serviceLogPath(a.Home, previewID, service, ".cloudflared.log")
	if err := ensureDir(filepath.Dir(logPath)); err != nil {
		return "", 0, "", err
	}
	lf, err := os.OpenFile(logPath, os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0o644)
	if err != nil {
		return "", 0, "", err
	}
	startOffset, err := lf.Seek(0, io.SeekEnd)
	if err != nil {
		lf.Close()
		return "", 0, "", err
	}
	cmd := exec.Command("cloudflared", quickTunnelArgs(originURL, hostHeader)...)
	cmd.Stdout = lf
	cmd.Stderr = lf
	cmd.SysProcAttr = &syscall.SysProcAttr{Setpgid: true}
	if err := cmd.Start(); err != nil {
		lf.Close()
		return "", 0, "", err
	}
	pid := cmd.Process.Pid
	go func() { _ = cmd.Wait() }()
	_ = lf.Close()
	url, err := waitForQuickTunnelURL(logPath, startOffset, 45*time.Second)
	if err != nil {
		_ = killProcessGroup(pid)
		return "", pid, logPath, err
	}
	a.recordEvent(previewID, "info", "tunnel.started", "cloudflared quick tunnel started", service, map[string]string{"pid": fmt.Sprint(pid), "url": url})
	return url, pid, logPath, nil
}

func waitForQuickTunnelURL(logPath string, offset int64, timeout time.Duration) (string, error) {
	re := regexp.MustCompile(`https://[-a-zA-Z0-9.]+trycloudflare\.com`)
	deadline := time.Now().Add(timeout)
	for time.Now().Before(deadline) {
		body, err := os.ReadFile(logPath)
		if err == nil {
			if offset < 0 || offset > int64(len(body)) {
				offset = 0
			}
			if m := re.Find(body[offset:]); m != nil {
				return string(m), nil
			}
		}
		time.Sleep(250 * time.Millisecond)
	}
	return "", fmt.Errorf("timed out waiting for cloudflared URL; see %s", logPath)
}
